- hosts: localhost
  tasks:

  - name: Install cert
    import_role:
      name: geerlingguy.certbot


  # vars:
  #   certbot_auto_renew_user: vrodi18
  #   certbot_auto_renew_minute: "20"
  #   certbot_auto_renew_hour: "5"

  # roles:
  #   - geerlingguy.certbot

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install Prerequisites
    import_role:
      name: prerequisites

  - name: Elk_Stack Repo
    import_role:
      name: elk_stack

  - name: Install ElasticSearch
    import_role:
      name: elasticsearch
  
  - name: Install Kibana
    import_role:
      name: kibana

  - name: Install Logstash
    import_role:
      name: logstash

  # - name: Install Filebeat
  #   import_role:
  #     name: filebeat

  # roles:
  # - role: lip-computing.ssl-certs
    

- hosts: remote
  tasks:

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Elk_Stack Repo
    import_role:
      name: elk_stack

  - name: Install Filebeat
    import_role:
      name: filebeat

